### ISSUE TITLE
https://live.amcharts.com/blahblah/ Failed to Embed

### ISSUE THREAD

**Issue by televators** [amcharts/amcharts-wp#1]
I'm using the latest version of the Wordpress plugin and the latest version of Wordpress. I had successfully embedded a chart a couple of days ago and it worked just fine. Today, I've got to embed like seven more charts on a site and the embeds aren't working. When I insert the chart using a live chart URL, it just says, "https://live.amcharts.com/blahblah/ Failed to embed". Nothing else. Just doesn't work. This is for a university website page that was built around being able to embed these charts. I don't see any JS errors in the console and everything appears to be working except the actual embedding. What do?!

**Comment by televators** [comment]
Okay, now all of a sudden the problematic chart is working... I was about to replace the plugin with the June commit's version but now it is working on this one chart. I'll report back if I have trouble with the next six.

**Comment by martynasma** [comment]
Let's chalk it up to a temporary glitch.

Let us know if the issue resurfaces.
